### ISSUE TITLE
Magento Connect

### ISSUE THREAD

**Issue by mbunge** [conlabz/Conlabz_CrConnect#5]
Magento Connect is containing an error in `Conlabz_CrConnect_Model_Observer::initCleverReach` Line 277, "$data not found". This error is already fixed on GitHub but still exists in Release at Magento Connect.

**Comment by dyron** [comment]
Thanks you for the info.
I finally managed to update Magento Connect Package with the version on GithHub.

**Comment by mbunge** [comment]
Thanks, we already updated to the latest version!
